#!/usr/bin/env python3
"""Build the Spotlight plugin payload from canonical repo-root sources."""

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "plugins" / "spotlight"

COPY_TREES = {
    "skills": ROOT / "skills",
    "agents": ROOT / "agents",
    "schemas": ROOT / "schemas",
    "scripts": ROOT / "scripts",
    "monitoring": ROOT / "monitoring",
}

GENERATED_FILES = {
    "AGENTS.md": ROOT / "AGENTS.md",
    "VALIDATED_DEPENDENCIES.md": ROOT / "VALIDATED_DEPENDENCIES.md",
    "skills-manifest.json": ROOT / "skills-manifest.json",
    "LICENSE": ROOT / "LICENSE",
    "DISCLAIMER.md": ROOT / "DISCLAIMER.md",
}

DOC_FILES = [
    "README.md",
    "epistemic-grounding.md",
    "fact-checking.md",
    "integrations.md",
    "integrations-roadmap.md",
    "investigating.md",
    "monitoring.md",
    "recovery.md",
    "rlm-benchmark-audit.md",
    "runtimes.md",
    "sensitivity.md",
    "spotlight-flow-vertical-visual.html",
    "structure.md",
    "vulnerabilities.md",
]


def reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)


def copy_tree(name: str, source: Path) -> None:
    destination = PLUGIN / name
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(
        source,
        destination,
        ignore=shutil.ignore_patterns(
            "__pycache__",
            ".DS_Store",
            "*.pyc",
            ".pytest_cache",
        ),
    )


def copy_docs() -> None:
    destination = PLUGIN / "docs"
    reset_dir(destination)
    for filename in DOC_FILES:
        source = ROOT / "docs" / filename
        if source.is_file():
            shutil.copy2(source, destination / filename)


def copy_integrations() -> None:
    destination = PLUGIN / "integrations"
    reset_dir(destination)
    for filename in ("README.md", "_preflight_base.py", "_runner.py", "preflight.py"):
        source = ROOT / "integrations" / filename
        if source.is_file():
            shutil.copy2(source, destination / filename)
    for integration_dir in sorted((ROOT / "integrations").iterdir()):
        if not integration_dir.is_dir():
            continue
        files = [
            integration_dir / "integration.md",
            integration_dir / "manifest.json",
            *sorted(integration_dir.glob("run_*.py")),
        ]
        existing = [path for path in files if path.is_file()]
        if not existing:
            continue
        target_dir = destination / integration_dir.name
        target_dir.mkdir()
        for path in existing:
            shutil.copy2(path, target_dir / path.name)


def write_generated_files() -> None:
    for name, source in GENERATED_FILES.items():
        if source.is_file():
            shutil.copy2(source, PLUGIN / name)
    (PLUGIN / "CLAUDE.md").write_text("@AGENTS.md\n", encoding="utf-8")
    (PLUGIN / "GENERATED_FROM_ROOT.txt").write_text(
        "Generated by scripts/build-plugin-payload.py from repo-root Spotlight sources.\n"
        "Do not edit copied skills, agents, docs, integrations, or schemas inside plugins/spotlight/ directly.\n",
        encoding="utf-8",
    )


def main() -> int:
    PLUGIN.mkdir(parents=True, exist_ok=True)
    for name, source in COPY_TREES.items():
        copy_tree(name, source)
    copy_docs()
    copy_integrations()
    write_generated_files()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
